version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    container_name: weather-api-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  weather-api:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env
    restart: always
    container_name: weather-api-container
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis_data:
